version: "2"
linters:
  default: all
  enable:
    - wsl_v5
    - gomodguard_v2
  disable:
    - noinlineerr
    - wsl
    - gomodguard
    - depguard
    - exhaustruct
    - funlen
    - mnd
    - testpackage
  settings:
    cyclop:
      max-complexity: 20
      package-average: 20
    gocognit:
      min-complexity: 40
    varnamelen:
      ignore-names:
        - tt
        - tc
      ignore-decls:
        - g *gpx.GPX
        - g gpx.GPX
        - i int
        - a ...any
        - err error
        - ok bool
        - id string
        - sb *strings.Builder
        - w http.ResponseWriter
        - rt http.RoundTripper
        - r *http.Request
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/stravaapi
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg/stravaapi
      - third_party$
      - builtin$
      - examples$
