minimum_pre_commit_version: '2.17'
exclude: 'pkg/stravaapi/.*'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      # check for unresolved merge conflicts
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
        args: ['--exclude-dirs', 'pkg/stravaapi']
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  # - repo: https://github.com/dnephin/pre-commit-golang
  #   rev: v0.5.1
  #   hooks:
  #     - id: go-fmt
  #     - id: go-mod-tidy
  #     - id: golangci-lint
  #       args: [ -E, gosec, -E, goconst, -E, govet, --timeout, 300s ]
  #     - id: go-imports
  #       args: [ -local, github.com/nce/strava2tourenbuch ]
